version: '3.7'

services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - mongo_data:/data/db
        command: mongod --logpath=/dev/null # --quiet

volumes:
    mongo_data:

